### ISSUE TITLE
Delineation - Delete Feature - Study Area shows red text after deleting associated feature

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#10]
Upon deleting a feature, the associated Study Area shows in red text.  The red text persists after deleting, and saving, and disabling editing.  
1. What is the intended duration of the red text?
2. Is the red text intended to be an indicator of unsaved edits (edits, including deletes)?

After an asset is deleted and successfully saved, the red text should return to a normal black text.

**Comment by GraceAi** [comment]
@leeensminger the red text intends to indicate number of selections in the study area has been changed. The text should become red when a feature is added or deleted.  Make sense to you?

**Comment by leeensminger** [comment]
@GraceAi Yes that makes sense, thank you.  Currently, the red text becomes black again when a new selection set is made, but I think we should remove the red text when the Enable Editing box is unchecked, and the edit session is closed.  

Low priority fix.

**Comment by leeensminger** [comment]
Red text at save has been removed from the widget?. Stakeholders are ok with this. Closing the open issue.
