### ISSUE TITLE
Delineation - Inspections - Cannot edit inspection where Inspection Date = current system date

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#13]
Within the Inspections tab of an asset, the system disables Editing when the Inspection Date is the same as the current system date.

To recreate:
1. Create New Inspection, with inspection date of today
2. Click Save
3. Click the feature record in the Feature Manager to refresh
4. The Inspection fields and associated Photo tab are disabled

![image](https://cloud.githubusercontent.com/assets/4103847/10604499/b032203e-76f2-11e5-839e-87270ffee2c3.png)

**Comment by GraceAi** [comment]
Fixed. Same bug in Review tab. Please wait for retest.

**Comment by leeensminger** [comment]
Confirmed fixed
