### ISSUE TITLE
Delineation  - Strem/Wetland/Other Points edits do not persist

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#14]
Within the General tab of a Stream Point, Wetland Point, or Other Point, upon updating the Flag Number or Class fields and saving, the system does not persist the edit.

To recreate:
1. While inside of an edit session, select a Stream/Wetland/Other Point feature
2. Within the General tab, update the Flag Number or Class field
3. Click Save
4. Click the point record in the Feature Manager again to refresh the Attribute Manager
5. Note the edit has not been persisted.

**Comment by GraceAi** [comment]
Fixed. Please wait for retest

**Comment by leeensminger** [comment]
Confirmed fixed
