### ISSUE TITLE
Mitigation Site Selection - Reviewer Photos - Photo phase value does not display within the data grid

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#16]
Within the Mitigation Reviews, when viewing a Review Photo, the Photo Phase value does not display in the data grid.  The value appears to be populating in the database.

To recreate:
1. Add a new Mitigation Review.  Set the Review Phase to a valid value. Save changes.
2. Add a Review Photo. Save changes.
3. The Photo Phase does not display.

The values in the database appear to be similar to "SDP", "DGP", etc.  That is fine, but we should be displaying the full text within the data grid - e.g., "Final Site Determination", or "Data Gathering".  This can be logic/code-based, or we can add a domain to this field.

![image](https://cloud.githubusercontent.com/assets/4103847/10607079/0d8c47b6-7705-11e5-9922-2959c16103e5.png)

**Comment by GraceAi** [comment]
Added a Review Phase domain to this field. Please wait for retest.

**Comment by leeensminger** [comment]
Confirmed fixed
