### ISSUE TITLE
Mitigation Site Selection - Reviewer Photos - Photo phase is updated when Reviewer Phase is updated

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#17]
Within the Mitigation Reviews, when the Review phase is updated and saved, the Photo Phase (REVIEWER_PHOTOS.REVIEWER_PHASE) is also updated to match.  This should not be the case.

The REVIEWER_PHOTOS.REVIEWER_PHASE should be updated equal to REVIEWER.REVIEW_PHASE only upon initial upload of the photo.  Subsequent updates to REVIEWER.REVIEW_PHASE should not trigger updates to REVIEWER_PHOTOS.

**Comment by GraceAi** [comment]
Fixed. Please wait for retest.

**Comment by leeensminger** [comment]
Confirmed fixed
