### ISSUE TITLE
Mitigation Site Selection - Reviewer Photos - Photo phase is not editable

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#18]
Within the Mitigation Reviews - Review Photos, the Photo Phase is disabled and is not editable.

This field should be automatically calculated by the system upon initial upload of the photo (should be set = REVIEWER.REVIEW_PHASE).  The system should not automatically update this field at any point after initial upload.  However, the user may update this field after initial upload.

Please reference bug #17 for related issue.

![image](https://cloud.githubusercontent.com/assets/4103847/10607479/ad0203f6-7707-11e5-88f6-fa5bfcd89799.png)

**Comment by GraceAi** [comment]
Fixed. Please wait for retest.

**Comment by leeensminger** [comment]
Confirmed fixed
