### ISSUE TITLE
Mitigation Site Selection - Move Geometry - Streams - Confirmation popup message inconsistent with feature type

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#19]
When moving geometry for a Stream or Other Site Selection or Asset feature, the confirmation message that is displayed references "Move Wetland Shape".  Please update to "Move Stream Shape", or "Move Other Shape".

To recreate:
1. Select a Stream Site Selection feature
2. Click Move to move geometry
3. Note that the confirmation message references Wetland

![image](https://cloud.githubusercontent.com/assets/4103847/10608229/1adec77a-770c-11e5-837c-90e1f2baae9e.png)

**Comment by GraceAi** [comment]
Updated it to "Move Shape". Please wait for retest.

**Comment by leeensminger** [comment]
Confirmed fixed
