### ISSUE TITLE
Selection - Query Builder - Input Value query returns inaccurate results

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#2]
Within the Selection Query Builder, when building a query where there is no domain value (ex: Project name), the system consistently returns 48 results, and include the following issues:
1. Each returned project is displayed in the grid multiple times.  I cannot identify what is driving the number of duplications.
2. Projects without the given project name are displayed.

To recreate:
1. Within Selection Query Builder, select Field Name - "PROJECT_NAME", Operator - "=", Input Value - "US 40 Improvements"
2. Click Add
3. Click Validate.  The popup indicates there are 48 selections.  Click OK.
4. Click Select.  The results returned include the following examples for project name "US 40 Improvements"
![image](https://cloud.githubusercontent.com/assets/4103847/10586003/25e6bc4e-7668-11e5-8b44-59221efc61df.png)

![image](https://cloud.githubusercontent.com/assets/4103847/10586012/2f2f3f1a-7668-11e5-914f-be54ca0540b1.png)

**Comment by vijme** [comment]
We are unable to replicate this in our environment. Can you please post the screenshot of the selection screen if you still have this issue?

**Comment by leeensminger** [comment]
The two screenshots below yield the results which were captured in screenshots in the original issue:

![image](https://cloud.githubusercontent.com/assets/4103847/10616151/a2286ef0-7731-11e5-91ac-6597b54186b0.png)

![image](https://cloud.githubusercontent.com/assets/4103847/10616160/af1f219e-7731-11e5-87f0-630c7f5761a4.png)

**Comment by leeensminger** [comment]
Retested - fixed.
