### ISSUE TITLE
Mitigation Site Selection - Add New Site Selection Feature - 6 Digit watershed value does not display in the data grid

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#20]
Upon adding a new Wetland/Stream/Other Site Selection feature, the 6 digit watershed value does not display in the data grid.  It appears the value is populating in the database, but is not displaying in the UI.

To recreate:
1. Add New site selection feature
2. Upon clicking Finish, navigate to the 6 digit watershed field in the General tab for the new feature.

![image](https://cloud.githubusercontent.com/assets/4103847/10608616/d166e7d8-770d-11e5-8a9e-4a11cd0e8d03.png)

**Comment by GraceAi** [comment]
@leeensminger it is data issue. Currently the 6 Digit domains are formatted as XX-XX-XX. But when generating a new feature, autopopulated 6 Digit field has this format: XXXXXX (from UNION_ALL_BASE table). Do you want us to update the 6Digit domains?

**Comment by leeensminger** [comment]
Yes, please update the domains to remove the "-".  Thanks!

**Comment by GraceAi** [comment]
Fixed. Available for retest
