### ISSUE TITLE
Mitigation Site Selection - Selection Quick Filters - Selecting a quick filter returns erroneous results

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#21]
Upon making a selection query using a quick filter, the system returns results that do not fit the selection criteria.

To recreate:
1. Within Mitigation Site Selection workflow, select an 8 digit watershed (ex: Honga River)
2. Apply Filter
3. In the Results tab, 57 Watersheds are returned.  Honga River watershed is not one of the results.

Reference bug #2 for similar issue on the Delineation side.

**Comment by GraceAi** [comment]
Fixed. Please wait for retest.

**Comment by leeensminger** [comment]
Confirmed fixed
