### ISSUE TITLE
Mitigation Site Selection - Add New Site Selection Feature - Mitigation Review photo count defaults incorrectly to 1

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#22]
Upon creating a new Site Selection feature, within the Mitigation Reviews tab, Photo sub-tab, the photo count ("Photo  x of y") displays "Photo 1 of 1", when there is not a photo displayed or a photo associated.

When a new Reviewer record is created, the photo count corrects to "0 of 0".

To recreate:
1. Create a new Site Selection feature
2. Navigate to the Mitigation Reviews tab
3. Navigate to the Photo sub-tab

![image](https://cloud.githubusercontent.com/assets/4103847/10612797/5bd66544-7720-11e5-85d6-33b2b52e875c.png)

**Comment by GraceAi** [comment]
Fixed. Please wait for retest.

**Comment by leeensminger** [comment]
Confirmed fixed
