### ISSUE TITLE
Mitigation Site Selection - Feature Manager Grid - Site Selection source displays only the domain code in the datagrid

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#23]
Within the Feature Manager of the Mitigation Site Selection workflow, the system displays 8 digit watershed, Site Selection Number, and Source.  The source (< site selection feature class >.SOURCE) reads from domain D_Source, and displays only the domain code.  The domain description should be displayed here.

![image](https://cloud.githubusercontent.com/assets/4103847/10613003/4a4be956-7721-11e5-8889-970e38546e11.png)

**Comment by GraceAi** [comment]
Fixed. Ready for retest
