### ISSUE TITLE
Map Controls - System does not zoom to Study Areas or Mitigation Sites

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#25]
Currently, there is no way to view Study Area or Mitigation Site geometry.  Please confirm the layer is turned on in the table of contents (which is currently not available in the widget).

If the layer is currently turned on:
The system should zoom to the geometry when it is selected in the Selection Manager (assuming Autozoom is checked on)

**Comment by GraceAi** [comment]
This is fixed. Please wait for retest.

**Comment by GraceAi** [comment]
I also added a Purchase Area graphic layer, so you can view the Purchase Area geometry.

**Comment by leeensminger** [comment]
Confirmed fixed
