### ISSUE TITLE
Delineation/Mitigation - Selection Quick Filter - 6 Digit watershed name / number return different results

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#27]
Within the Selection Quick Filters, the system returns different results when selecting by 6 digit number, and by 6 digit name.  This appears to be unaffected by the umbrella workflow (mitigation, delineation).  The same issue is present within the 8 digit watershed selection process as well. 

The issue is not specific to one, or a set, of watersheds, but seems to be that selecting 6 or 8 digit NUMBER yields no results, but selecting the equivalent NAME does return results.

To recreate in the Delineation workflow:
1. Select 6 digit number 02-14-01 in the Selection Quick Filter.  The name Lower Potomac River Area is automatically selected in the Name dropdown.
2. Click Apply Filter.  No results are found. Click OK in the popup.
3. Clear Filter
4. Select 6 digit name Lower Potomac River Area
5. Click Apply Filter.  Seven (7) projects are returned.

![image](https://cloud.githubusercontent.com/assets/4103847/10637048/449c5ef4-77d1-11e5-8b67-31ba53e56f58.png)

**Comment by GraceAi** [comment]
Fixed. Same issue with issue #21 . Please wait for retest

**Comment by leeensminger** [comment]
Confirmed fixed
