### ISSUE TITLE
Delineation/Mitigation - Selection Query Builder - searching by "Area/Length" needs additional operators

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#28]
Within the Selection Query Builder, when selecting based upon field name "Area/Length", the following operators should also be available:
- Greater Than
- Greater Than or Equal To
- Less Than
- Less Than or Equal To

![image](https://cloud.githubusercontent.com/assets/4103847/10637261/89bae482-77d2-11e5-9767-2f8447844eb7.png)

**Comment by GraceAi** [comment]
Fixed. Please wait for retest

**Comment by leeensminger** [comment]
Confirmed fixed
