### ISSUE TITLE
Delineation/Mitigation - Select By Map - Re-Enable Map Tool is disabled

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#29]
When Selecting by Map, the Re-Enable Map Tool is disabled, which forces the user to cancel the selection in order to re-draw the selection polygon.

![image](https://cloud.githubusercontent.com/assets/4103847/10637411/8621f454-77d3-11e5-87aa-c9380f1adf5b.png)

**Comment by GraceAi** [comment]
Fixed. Please wait for retest

**Comment by leeensminger** [comment]
Confirmed fixed
