### ISSUE TITLE
Selection - Map Selection - Results

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#3]
When using the Select by Map, and selecting a Stream Asset, the widget correctly returns the Project for which the selection is associated.  The user must then drive down through potentially multiple Study Areas to find and select the correct feature, and then begin working with it.  

Is it plausible to return the Project, and make both the associated Study Area selection and the feature selection automatically within the system?

So, when the user did a Select by Map, the system would immediately show the following screen (where Project, Study Area, and Feature are already selected and displayed):

![image](https://cloud.githubusercontent.com/assets/4103847/10586943/c90062d2-766c-11e5-8de7-608781f3334e.png)

**Comment by GraceAi** [comment]
@leeensminger , How do you select a Stream Asset while using Selected by Map? When performing Selection by Map, multiple projects/study areas/assets might be returned. I am not sure how to grab the specific Asset and make it selected.

**Comment by leeensminger** [comment]
Agreed
