### ISSUE TITLE
Delineation/Mitigation - Selection Quick Filters - Apply Filter becomes enabled and returns results without a selected Filter

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#30]
Within the Selection Quick Filters, for Delineation project type, the Apply Filter button becomes enabled immediately upon selecting the Project Type.  Upon clicking Apply Filter, the system returns 7 projects.

Upon selecting a Mitigation project type, the Apply Filter button becomes enabled immediately upon selecting a Mitigation Type (5 projects returned for Mitigation / Assets).

Is there functionality intended to be here?  If not, then the Apply Filter should remain disabled until a filter selection is made.

To recreate:
1. Select any project and / or mitigation type
2. Click Apply Filter.

![image](https://cloud.githubusercontent.com/assets/4103847/10637662/d3b48d52-77d4-11e5-9fdf-3a2e4352c181.png)

**Comment by GraceAi** [comment]
@leeensminger I think this would allow user to view all of the projects/watersheds. We have the similar function in TMDL widget. Let me know what you think.

**Comment by leeensminger** [comment]
@GraceAi Great, thats what I thought might be the intent, and I think thats great.  Let's keep the Apply Filter as it currently is, and let users view all projects/watersheds.
