### ISSUE TITLE
Delineation/Mitigation - Editing - Closing edit session with unsaved edits does not prompt for confirmation message

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#31]
The system does not display a confirmation message if the user attempts to close the system with unsaved edits.

To recreate:
1. Click Enable Editing to open edit session
2. Select a feature and make an edit.
3. Click Enable Editing to close edit session

The system should display a confirmation message here, indicating that there are unsaved edits / would you like to continue.  This should include OK/Continue and Cancel buttons.

**Comment by GraceAi** [comment]
Fixed. Please wait for retest

**Comment by leeensminger** [comment]
Confirmed fixed
