### ISSUE TITLE
Delineation/Mitigation - Selection Query Builder - Binding operator is not cleared after Clear Query

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#32]
Within the Selection Query Builder, the binding operator value is not cleared, after clicking the Clear Query button.  The workflow to arrive at this issue is very specific:
1. Select a valid Project Type
2. Select any Field Name (ex: County)
3. Select an Operator (ex: "=")
4. Select a Unique Value (ex: Allegany)
5. Click Add
6. Select any Binding Operator (ex: AND)
7.  Do not build the rest of the query.  Click Clear Query button.  The operator AND remains displayed within the Binding Operator dropdown menu.

The issue does not affect building or validating a second/fresh query.

Screenshot at step 6:
![image](https://cloud.githubusercontent.com/assets/4103847/10638780/987a54aa-77da-11e5-8146-c094f72daf5f.png)

Screenshot after step 7:
![image](https://cloud.githubusercontent.com/assets/4103847/10638792/a4f52fa2-77da-11e5-8af0-0636d6e6709e.png)

**Comment by GraceAi** [comment]
fixed. Please wait for retest

**Comment by leeensminger** [comment]
Confirmed fixed
