### ISSUE TITLE
Mitigation Site Selection - Results Counts are mismatched to Feature Manager counts

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#33]
For Mitigation Site Selections, within the Results tab, the number of selections shown in the Selection Manager inconsistently does not match the numbers given in the Feature Manager.

Please confirm, that the intended logic for Mitigation Site Selection workflow, the # Selections per each watershed in the Selection Manager should equal the sum of counts for each feature type in the dropdown in the Feature Manager.

To recreate:
1. Select Project Type = Mitigation // Site Selection
2. Select a Selection Quick Filter for County = Baltimore
3. Click Apply Filter
4.  Select 8 digit watershed = Gunpowder River, where the Selection Manager shows # Selections = 1, but within the Feature Manager, it shows 4.
5. Also view watershed name Liberty Reservoir, where Selection Manager shows # Selections = 2, Feature Manager shows 22.  

Watersheds Prettyboy Reservoir and Patapsco River L N Br is also mismatched.  Lower Wicomico River and Lower Gunpowder Falls appear correct.
May be related to #27 and #21 

![image](https://cloud.githubusercontent.com/assets/4103847/10645259/deafaad6-77fa-11e5-8e94-b91ca59d1f10.png)

![image](https://cloud.githubusercontent.com/assets/4103847/10645006/773e6686-77f9-11e5-9c46-4339572161f2.png)

**Comment by GraceAi** [comment]
fixed. ready for test.
