### ISSUE TITLE
Services: getStudyAreas should return list for sub projects

### ISSUE THREAD

**Issue by sfabijanski** [leeensminger/OED_Wetlands#34]
I created a sub-project and assigned some new study areas to it. However, the getStudyAreas service  (Project/GetStudyAreas) does not return the list of assigned areas for sub projects. I believe it should, particularly since there is a hard dependency on deleting the record if study areas are assigned. User should see direct children. The same should apply to mitigation sites.

What I think should happen with a request is:
1) if project for the supplied project_id represents a sub-project, return assigned study areas (does not seem to work)
2) if project is parent, return directly assigned study areas, plus any assigned to child projects (looks like this is current )

-sf

**Comment by vijme** [comment]
@sfabijanski I think the service you are talking about is Asset/GetProjectStudyAreas. I realized that that service needs to be specifically for Results tab, that passes only parent project. I have modified the 
Projects/GetStudyAreas service to optionally accept a projectID. This will list the study areas for both parent and subproject ID's. Please let me know if you still have issues.

**Comment by sfabijanski** [comment]
Looks like projectID is not optional on Projects/GetStudyAreas--with no projectID I get empty list. You were correct regarding app's use of Asset/GetProjectStudyAreas. I've updated reference back to the Projects endpoint.

**Comment by vijme** [comment]
Looks like the service just got updated. can you please try now

**Comment by sfabijanski** [comment]
Yes study areas is working as expected now. Is getMitSites changed to reflect this as well? Should I open as a separate ticket?

**Comment by vijme** [comment]
Mit Sites is also corrected to reflect this

**Comment by sfabijanski** [comment]
I see it. I couldn't find a good test project until just now.
