### ISSUE TITLE
Request to AddMitSite failes

### ISSUE THREAD

**Issue by sfabijanski** [leeensminger/OED_Wetlands#35]
Some confusion regarding how to post a request to Project/AddMitSite. I attached the projectID as part of the json package and received an error. Please evaluate:

request url: http://vm-city102/Wetland/api/Project/AddMitSite?

request body:
Referer: http://localhost:8000/flexviewer_2.2/gov/sha/widgets/wetlands/Wetland.swf Content-type: application/json Content-length: 677 {"mitsite":{"OFFSITE_PERMIT_OTHER_DESC":"","MITIGATION_AREA_STATUS":"PENDING","OFFSITE_PERMIT_WQC":"","OFFSITE_PERMIT_WQC_EXPIRATION":"","PROJECT_MANAGER":"","OFFSITE_PERMIT_CAC":"","ADC_LOC":"","SHAPE":"POLYGON ( ( 1547536.299765808 294918.0327868854,1559948.4777517566 288711.94379391114,1553742.3887587823 276299.7658079626,1547536.299765808 294918.0327868854 ) )","OFFSITE_PERMIT_WWC":"","OFFSITE_PERMIT_ES":"","CONSTRUCTION_CONTRACT":"","SITE_DESCRIPTION":"","COMMENTS":"","ON_SITE":"1","PROJECT_ID":"796e266a-5158-40a2-944d-67220f0a4474","OFFSITE_PERMIT_OTHER":"","FAP_NUMBER":"","SITE_NAME":"test sf","PDMS_NUMBER":""},"projectID":"796e266a-5158-40a2-944d-67220f0a4474"}

response:
<Error><Message>No HTTP resource was found that matches the request URI 'http://vm-city102/Wetland/api/Project/AddMitSite'.</Message></Error>

**Comment by vijme** [comment]
@steve, i think thats because the service is supposed to receive projectID from the url, and mitsite object from the body. Please let me know if you still have issues

**Comment by sfabijanski** [comment]
It causes a bit of undue extra work on the client application part because I'll need to break out of a pattern to handle this one exceptional case. If the service can be made to handle the parameter in the post body I could  be done.

**Comment by vijme** [comment]
Would it be easier if I add an additional field called "PROJECT_ID" inside mitsite object? Let me know if that works, i will change the service accordingly.

**Comment by sfabijanski** [comment]
Yes, if it is easy to adjust on your end, I can make the change quickly on the client side. I would also need the EditMitSite endpoint to follow the same pattern. Let me know when implemented. Thanks.

**Comment by vijme** [comment]
@sfabijanski , I have changed the webservice to include PROJECT_ID inside mitsite object. For edit, we only need mitigation_site_id as a key, and project_id is not needed. So there will not be any change to existing editMitSite service.

**Comment by sfabijanski** [comment]
Add new working. Closing this.  However, watershed 8 digit is not populating. Opening new item.
