### ISSUE TITLE
AddMitSite does not populate 8 digit watershed

### ISSUE THREAD

**Issue by sfabijanski** [leeensminger/OED_Wetlands#36]
When adding a new mitigation site, the database does not add an 8 digit watershed. This prevents editing of the site in the application as the empty WATERSHED_8DIG_ID field is marked as nonEditable and validation requires it to be not null.  The empty field prevents the user from continuing.

**Comment by vijme** [comment]
@sfabijanski, the 8 digit watershed is stored in db, but it is not retrieved in the GetMitSites service.  assume you are using GetMitSites service to get the mitigation site details too. So, I have edited the getMitSite sp to return all the mitigation_site fields. Let me know if this works.

**Comment by sfabijanski** [comment]
It looks like the values passed back are the guid ids for the watershed table, not the number codes. I checked the domain for the watersheds and they are passing the numerical codes normally associated with the watersheds.

**Comment by sfabijanski** [comment]
Looks good. Closing.
