### ISSUE TITLE
Projects - Associated Mitigation Sites do not display in the datagrid

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#37]
The Mitigation Sites tab does not display any records.  I confirmed within the database that project ID 8cf9ce93-1f20-4a24-b32b-ddb97f19c49f (MD 124 Lane extension) is associated to 2 mitigation sites:

20f37616-5d1d-4d20-a09a-f3f01b8a6b0d
33556824-9b44-46f5-8dc7-8d85a9ed9475

No records are displayed within the mitigation sites tab.

![image](https://cloud.githubusercontent.com/assets/4103847/10715163/cf9269dc-7ae1-11e5-82e8-4c321889f3ac.png)

**Comment by sfabijanski** [comment]
Latest version pushed to repo contains this feature. Please test and confirm after next server refresh.

**Comment by leeensminger** [comment]
Confirmed fixed
