### ISSUE TITLE
Projects - Filter by selected project clears Sub-Projects tab

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#38]
When a parent project is selected, with Sub-Projects displayed in the Sub-Projects tab, toggling off the Filter by selected project checkbox clears the Sub-Projects list.  Re-selecting the parent project re-populates the list.

To recreate:
1. Toggle ON the Filter by selected project checkbox
2. Select project with child subprojects (ex: MD 24 Improvements)
3. Three sub projects are displayed
4. Toggle OFF the Filter by selected project checkbox
5. The Sub-Projects tab clears
6. Re-select the parent project in the Selection Manager / top data grid.  The Sub-Projects list repopulates.

At initial selection, with the Filter by selected project ON:
![image](https://cloud.githubusercontent.com/assets/4103847/10715196/98dc6ff8-7ae3-11e5-9f18-0eee270ee9cf.png)

Toggle the filter by selected project OFF:
![image](https://cloud.githubusercontent.com/assets/4103847/10715198/a21cd9cc-7ae3-11e5-9a88-df76748137ce.png)

**Comment by sfabijanski** [comment]
Issue resolved in last round of commits. Please review and close.

**Comment by leeensminger** [comment]
Confirmed fixed
