### ISSUE TITLE
Projects - Editing existing Study Area dissociates the Study Area from the project

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#39]
Upon saving an Edit to an existing Study Area, the Study Area is removed from the Study Area tab datagrid.  I confirmed in the database that the STUDY_AREAS.PROJECT_ID field is actually being nulled upon save.  

To recreate:
1.  Select a project with an existing study area, enable editing, and open the Study Area editing popup window.
2. Click Apply to save edits (no edit actually necessary).  
3. The Study Area is removed from the data grid.  In the database, the relationship key is nulled.

**Comment by sfabijanski** [comment]
Working in my latest dev. I verified the repo reflects this change. Application needs to be updated and retested.

**Comment by leeensminger** [comment]
Confirmed fixed
