### ISSUE TITLE
Projects  - Mitigation Strategy tab label

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#40]
The tab label for the existing Mitigation Strategy should be updated to read "Mitigation Summary".

![image](https://cloud.githubusercontent.com/assets/4103847/10715263/4358c22c-7ae6-11e5-8d4f-9a7037584e33.png)

**Comment by sfabijanski** [comment]
Done and pushed to repo. Please confirm and close after test server update.

**Comment by leeensminger** [comment]
Confirmed fixed
