### ISSUE TITLE
Projects - Mitigation Strategy data grid does not display data

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#41]
The Mitigation Strategy/Summary tab does not appear to populate associated records in MITIGATION_LEDGER.  I confirmed this for a Project (MD 24 Improvements) that has an associated record in MITIGATION_LEDGER table.  The empty data grid is also unaffected by the Filter by selected project checkbox (please confirm that this checkbox is intended to impact Mitigation Strategy/Summary and Sub-Projects tabs).

![image](https://cloud.githubusercontent.com/assets/4103847/10715296/ef13df42-7ae7-11e5-8e6b-370036cd20e1.png)

**Comment by sfabijanski** [comment]
The most recent version populates when the project filter checkbox is checked. I just confirmed the test version does not have this funtionality. I pushed this about midday yesterday the app needs a refresh. One problem with the grid is that it shows as editable, though it is not meant to be until double clicked and launced in the editing window.

**Comment by leeensminger** [comment]
Confirmed fixed
