### ISSUE TITLE
Update Associations for Study Area does not update data

### ISSUE THREAD

**Issue by sfabijanski** [leeensminger/OED_Wetlands#44]
Posting to the update association for study areas receives a "succeed" response, but the data does not appear to update. The below request posts two study area ids ( study area nums =  090003--already associated and 090001--newly associated ). The getStudyAreas endpoint only returns data for 090003 for the project. Details:

url:
    http://vm-city102/Wetland/api/Project/UpdateProjectStAreas?

request:
Referer: http://localhost:8000/flexviewer_2.2/gov/sha/widgets/wetlands/Wetland.swf Content-type: application/json Content-length: 186 {"PROJECT":"881aaf2e-80bb-4d75-897c-174666abaefe","MITSITE_STAREA_ID":[{"STUDY_AREA_ID":"15cbb88d-e551-4d03-b0be-6efe37d2bb74"},{"STUDY_AREA_ID":"f1982420-6f3e-4054-96a1-8699feddec48"}]}

response:
Succeed

**Comment by vijme** [comment]
I think it is the same error as the previous one. You may need to change the STUDY_AREA_ID to STRING_NAME. The following worked:
{"PROJECT":"881aaf2e-80bb-4d75-897c-174666abaefe",
"MITSITE_STAREA_ID":[{"STRING_NAME":"15cbb88d-e551-4d03-b0be-6efe37d2bb74"},
{"STRING_NAME":"f1982420-6f3e-4054-96a1-8699feddec48"}]}

**Comment by sfabijanski** [comment]
STRING_NAME works.
