### ISSUE TITLE
Update Associations for Mitigation Site: empty array does not empty associations.

### ISSUE THREAD

**Issue by sfabijanski** [leeensminger/OED_Wetlands#45]
If a user removes all associations to mitigation sites and applies changes, the response is successful. However, the sites that were previously associated remain associated. The service should continue to remove all associations and not assign new ones in the event of an empty collection.

**Comment by vijme** [comment]
Fixed. Please check.

**Comment by sfabijanski** [comment]
Tested and confirmed after latest service update.
