### ISSUE TITLE
Results Tab: Adjusting a moved feature causes a duplicate spatial feature`

### ISSUE THREAD

**Issue by sfabijanski** [leeensminger/OED_Wetlands#46]
I moved a selected feature and approved the move. I immediately hit "Move" to move the feature back to where it started. Instead, it duplicated the feature on the map. I was able to repeat this process and create a third spatial artifact.
<img width="524" alt="moved_feature_duplicate" src="https://cloud.githubusercontent.com/assets/1973336/10757784/62668fd4-7c83-11e5-9ede-c02931af7365.PNG">

**Comment by GraceAi** [comment]
@sfabijanski thanks. Fixed. Please update the code.

**Comment by sfabijanski** [comment]
Verified in my version. Closing.
