### ISSUE TITLE
Projects - New contracts not available in Projects//Contract Number dropdown

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#49]
After successfully adding a new contract, the contract is not available to select from, within the Add New or Update projects Contract Number dropdown menu.

To recreate:
1. Create new contract
2. Initiate create new project
3. Click the contract number dropdown.  The previously created contract is not present.

**Comment by sfabijanski** [comment]
Functionality was pushed to repo yesterday evening. I just verified this works in my local dev. @johnshiu will need to refresh testing server.

**Comment by leeensminger** [comment]
Confirmed fixed
