### ISSUE TITLE
Projects - Add New Project - Sort dropdown menu values

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#50]
When displaying the Contract Number dropdown in the Add New Project/Subproject Workflow, the Contracts should be sorted alphanumerically.  

All dropdown domains should be sorted in the same manner.  I will comment each specific domain for the Projects tab inside this same bug unless directed otherwise.

**Comment by vijme** [comment]
@sfabijanski I have updated the backend procedures. Please check

**Comment by leeensminger** [comment]
Confirmed fixed
