### ISSUE TITLE
Projects - Add New Project - text label is incorrect

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#51]
When selecting a feature type to add (project, contract, subproject, etc.) the text label reads "File Type".  Please update to "Feature Type"

![image](https://cloud.githubusercontent.com/assets/4103847/10764381/3e681000-7ca4-11e5-85ee-b25ba1219ba2.png)

**Comment by sfabijanski** [comment]
Completed and pushed to repo. Closing as it's only a text update.
