### ISSUE TITLE
Delineations - Results tab - Attribute Manager - General Tab - Remove non-workflow related fields

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#54]
Within the General tab for Delineations, please hide the following Mitigation-specific fields:

a.  Last Inspection Date
b.  Monitoring Start Date
c.  Monitoring Start Date (Act)
d.  Annual Report Required
e.  Mitigation Asset
f.  Mitigation Type
g.  Total Mitigation Surplus

![image](https://cloud.githubusercontent.com/assets/4103847/10765080/8d6982a8-7ca7-11e5-9ad4-fbf174de1008.png)

**Comment by leeensminger** [comment]
Appears fixed

**Comment by leeensminger** [comment]
Please re-enable these fields within the Mitigation Workflow.  If we cannot show different grids in the Delineation and Mitigation workflows, then we should show them all, and perhaps we can sort the fields listed above to the bottom of the datagrid.

**Comment by GraceAi** [comment]
Re-enabled these fields within Mitigation workflow. Please retest it after test site and web service are updated.

**Comment by leeensminger** [comment]
Tested and confirmed OK
