### ISSUE TITLE
Delineations - Results tab - General tab - Rename field label "Creation Firm"

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#55]
Please rename the label "Creation Firm" to read "Delineated By:".

![image](https://cloud.githubusercontent.com/assets/4103847/10765155/cc3ecf42-7ca7-11e5-9c13-3ca098c9b135.png)

**Comment by GraceAi** [comment]
Fixed. Please retest it after server is updated.

**Comment by leeensminger** [comment]
Confirmed fixed.
