### ISSUE TITLE
Delete Request fails for Mitigation Site

### ISSUE THREAD

**Issue by sfabijanski** [leeensminger/OED_Wetlands#56]
Trying to delete a mitigation site that has no watershed information and no assigned projects (as least when I attempted to delete). When I post a delete, I get an IO Error (417, Dependencies Exist). I can't determine what dependencies exist. Details follow.

url:
http://vm-city102/Wetland/api/Project/DeleteMitSite?

request:
Referer: http://localhost:8000/flexviewer_2.2/gov/sha/widgets/wetlands/Wetland.swf Content-type: application/json Content-length: 770 {"OFFSITE_PERMIT_CAC":"test","SHAPE":"","OFFSITE_PERMIT_ES":"test","PURCHASE_AREA_ID":"923e256d-b5b1-4fb1-93c2-df5b644e098d","SITE_DESCRIPTION":"test","OFFSITE_PERMIT_OTHER":"test","SITE_NAME":"test","OFFSITE_PERMIT_OTHER_DESC":"test","TOTAL_AREA_ACRES":"26.45268189","OFFSITE_PERMIT_WQC":"test","TOTAL_MITIGATION_CREDIT_ACRES":"26.45268189","ADC_LOC":"test","OFFSITE_PERMIT_WQC_EXPIRATION":"08/20/2015","TOTAL_MITIGATION_CREDIT_LF":"2666.891843","COMMENTS":"test","CONSTRUCTION_CONTRACT":"test","OFFSITE_PERMIT_WWC":"test","WATERSHED_8DIG_ID":"","FAP_NUMBER":"test","ON_SITE":"1","PROJECT_ID":"","MITIGATION_AREA_STATUS":"ACCEPTED","PDMS_NUMBER":"4","MITIGATION_SITE_ID":"c0de7f41-5cac-4d39-8d11-85d1f2a3caa7","MITIGATION_SITE_NUMBER":"141001","PROJECT_MANAGER":"test"}

response:
Delete Mit Site Error: Dependencies Exist

**Comment by vijme** [comment]
@sfabijanski, asset df163ff3-87f5-4e8e-b052-c9c046ae7fa9 is associated to this mitigation site. A mitigation site cannot be deleted if it has assets or documents associated to it

**Comment by sfabijanski** [comment]
OK. But there error from the service is generic and does not provide this information. Also, @GraceAi , is there a way to see the assigned assets to a mitigation site? And, @johnshiu , is the best way to handle dependencies through throwing an error, or with 200 and the error message inside.

**Comment by sfabijanski** [comment]
Services working as intended. Handling on client site. Closing.
