### ISSUE TITLE
Projects / Selection - New Study Area or Mitigation Site is not available for selection

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#58]
After creating a new Study Area or Mitigation Site, the recently created feature is not available within the Selection tab.
1. Create new study area
2. Return to selection tab
3. Select project type = delineation
4. Click the Study Area ID dropdown, and the new study area is not present

**Comment by sfabijanski** [comment]
I'm handing off to Grace as she knows better what is going on to trigger changes on that tab. Here is the pertinent information to get her started.

In the WetlandsComponent my handler function for all handled services updates is `handleProjectServiceRequestComplete`. Within that method is a `refreshActions` object. Each feature has it's own section in refreshAction. She can add a function to the projects section array to have it called at the appropriate time. All  functions are passed the currently selected projectID from the projectsTab. Post any questions here and I'll answer as best I can.

```
    mitigationSite: {
        all: projectsSvcs.getMitigationSites,
    project: [ projectsSvcs.getProjectMitigationSites, ***ResultsFunctionHere*** ]
    }
```

**Comment by GraceAi** [comment]
@sfabijanski , thanks for the instruction. I added some code to fix this issue. Please update to head.

**Comment by sfabijanski** [comment]
@leeensminger  I pulled the code and it looks good. It's ready to close if you have the latest in testing.

**Comment by johnshiu** [comment]
This should be at SHA Test already.

**Comment by leeensminger** [comment]
Tested and confirmed OK
