### ISSUE TITLE
Create New Misc. Credit - Credit amounts should not be required fields

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#59]
Adding a new Misc Credit item requires the user to enter Credit Amt, in both acres and LF.  One of two things needs to happen:
1. Update both of these fields to not required, OR
2. Application logic may check these fields for null prior to save, then populate the nulls = 0.

![image](https://cloud.githubusercontent.com/assets/4103847/10799443/3a2cc082-7d83-11e5-869a-26fc1a2dffcb.png)

**Comment by sfabijanski** [comment]
Reassigning to Viji. This is controlled by the validation objects created from the getTableInfo request. Updating there will flow through the application.

**Comment by johnshiu** [comment]
This should be resolved at SHA.

**Comment by leeensminger** [comment]
Tested and confirmed OK
