### ISSUE TITLE
Create New Misc. Credit - Wizard header should not reflect project 

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#60]
When adding a new Misc Cred, the title of the header window should be updated to reflect that we are not creating a new project.  

options:
1. update to New Feature Wizard for any Create operation
2. Update this workflow to New Misc. Mitigation Feature Wizard

@sfabijanski I'm defining this as low priority / enhancement.  While not critical per the requirements, this should ideally be fixed before final deployment, and I'd rather you focus on smoothing out the core functionality and some of the other issues you might have logged in your todo list.

**Comment by sfabijanski** [comment]
Option 1 done and checked in.

**Comment by leeensminger** [comment]
Tested and confirmed OK
