### ISSUE TITLE
Projects - Study Areas should not display time created

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#61]
Within the Study Areas tab of the Projects tab, the Date Created shows the time created, but all are zeros.  The system is probably not capturing time of creating, so we can just display date here and wipe the time.

**Comment by sfabijanski** [comment]
On my local list. Will address when as higher priority items get completed.

**Comment by sfabijanski** [comment]
Completed this and pushed to repo. Also added project manager to datagrid since there was so much room left after removing the times portion.

**Comment by leeensminger** [comment]
Tested and confirmed OK
