### ISSUE TITLE
Results - Feature list maintains previous display

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#63]
Within the Results tab, after viewing asset points, the system maintains some legacy components of the Feature Manager grid.  See image and steps to recreate below.

```
1. View a Study Area with points associated to it
2. Select and view the points in the Feature Manager
3. Click Selections tab
4. Choose a Mitigation Workflow and apply filter
```

![image](https://cloud.githubusercontent.com/assets/4103847/10802211/d7fb6008-7d91-11e5-8240-a06017dce16c.png)

**Comment by GraceAi** [comment]
Fixed. Please retest it after test site is updated.

**Comment by leeensminger** [comment]
Tested and confirmed OK
