### ISSUE TITLE
Mitigation Reviews - Erroneous required fields

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#64]
The following fields are required fields, but should be nullable:

```
• SITE_SELECTION_PHASE.AGENCY_APPROVAL
• SITE_SELECTION_PHASE.NEPA_REVIEW_APPROVAL
• FINAL_SITE_DETERMINATION_PHASE.NEPA_ISSUES
• FINAL_SITE_DETERMINATION_PHASE.ORE_APPROAL
• FINAL_SITE_DETERMINATION_PHASE.SELECTION_LETTER_SENT
• SITE_ACQUISITION_PHASE.ACQUISITION_APPROVAL
• SITE_ACQUISITION_PHASE.ACQUISITION_LETTER_SENT
```

**Comment by johnshiu** [comment]
This should be resolved at SHA.

**Comment by leeensminger** [comment]
Tested and confirmed OK

**Comment by leeensminger** [comment]
This has resurfaced.  In the latest xml provided to you (dated 20160108, on KCI's FTP) I updated these fields to allow nulls.  Please reload database for testing.

**Comment by johnshiu** [comment]
These fields will be updated in the next data load.
