### ISSUE TITLE
Logging in to SHA test environment produces login bug

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#66]
Upon accessing the widget at SHA environement, the error message below is displayed.  Also, there is no user login screen to enter user credentials - but not sure if that is because of the nature of the test environment, or not.

![image](https://cloud.githubusercontent.com/assets/4103847/10802761/0063f2fa-7d95-11e5-81d7-10e74ef1dadd.png)

**Comment by johnshiu** [comment]
I can't seem to replicate this. Does the production SHA environment work for you? http://shagbegis1/egis 

http://shagbdapp/egis is loading for me. Perhaps try clearing cache again?

**Comment by leeensminger** [comment]
I cleared cache again and restarted IE, but still caught the same error, immediately upon accessing the site.

The SHA production environment does not produce the error.

**Comment by johnshiu** [comment]
I tested with my machine (SHAOPPEPC608) and another (SHAOPPEPC604), and both work...

Which machine are you testing from? Does it work in an alternative browser? Can you try the 604 machine to see if it works?

**Comment by leeensminger** [comment]
I'm testing from two VMs: SHAOEDVD309, and SHAOEDVD306.  

When testing from 306, I did not initially receive this Application Error.  However, I did receive 2 messages with OK buttons, about 'unable to display map services' (I did not screen shot and was unable to reproduce these results), and the basemap and content loaded without problem.  

After clearing cache and retesting this same methodology, I received the same Application Error as originally identified here.  I then reproduced this several more times.

Testing from 309 consistently reproduces the issue initially identified.

I'm trying to connect to the 604 machine via RDP while VPNd to SHA's network.  I'm unable to connect; the machine name is not able to be found.  

I'll reach out to Dustin to see if he can connect tonight.  He is also on site at SHA first thing tomorrow morning, and we can try it there.

**Comment by johnshiu** [comment]
Thanks the update, Lee. The 2 map service errors will show up if you don't have an internet connection, I believe, as some basemaps are located off-site. You can OK out of them and the application will run fine.

Also, the two VMs I'm using are DSED machines, not OED ones, so perhaps there is an access issue with access to the server from other machines outside of the DSED ones?

**Comment by leeensminger** [comment]
That seems certainly plausible.  I just attempted another reconnection, and did not receive the error.  Then restarted IE and got the error.

This doesn't affect usability of the widget that I've seen so far.  I can "x" out and load the Wetland content, so I'm thinking let's table this until tomorrow, and Dustin and I will test further when on-site.

**Comment by leeensminger** [comment]
We have not had this issue so far today at SHA.  Must have been specific to the machines/methods used to access SHA dev environment last night.  Closing this issue for the time being.
