### ISSUE TITLE
Mitigation Reviews - Photos - Uploading Review photo without positional coordinates returns error

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#68]
When uploading a Mitigation Review photo, which is not geoenabled, the system will load the photo - but upon clicking Save, the system produces the error below.  NOTE that this only occurs within SHA environment at this time.  

![image](https://cloud.githubusercontent.com/assets/4103847/10803164/43848f20-7d97-11e5-8b26-a31cb1de2a91.png)

**Comment by johnshiu** [comment]
This should be resolved at SHA.

**Comment by leeensminger** [comment]
Tested and confirmed OK with latest update (at KCI dev)
