### ISSUE TITLE
Documents - Feature Documents - File Type displays domain code

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#7]
Within the Feature Documents data grid, when a file is uploaded, the File Type in the data grid is displayed as the domain code.  The domain description should be displayed.  

![image](https://cloud.githubusercontent.com/assets/4103847/10588695/6e27df8a-7675-11e5-8239-8cac3d783fb7.png)

**Comment by GraceAi** [comment]
fixed. Please wait for retest

**Comment by leeensminger** [comment]
Confirmed fixed
