### ISSUE TITLE
Delineation - Archive - "user" field always displays "WIDGET"

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#70]
Within the Feature Archives, the User always is WIDGET.  This should be populated with the user name of the user who performed the geometry edit.  In the image below, I created the original shape, and modified twice.

Low priority.

![image](https://cloud.githubusercontent.com/assets/4103847/10805895/bba0aa4c-7da7-11e5-9cb5-b4a9c6cb9ef0.png)

**Comment by GraceAi** [comment]
Fixed. Please retest it after test site is updated.

**Comment by leeensminger** [comment]
Tested and confirmed OK
