### ISSUE TITLE
File Attachment - System defaults to file type of Custom Files

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#71]
When attaching a file (Study Area Documents, or in Documents tab for asset workflows) when the system displays the file browser, the type defaults to Custom Files, and files are not displayed in the window.  The user must select the dropdown and choose All Files to select and attach files.

Custom Files:
![image](https://cloud.githubusercontent.com/assets/4103847/10806412/71f99990-7dab-11e5-971d-eb55643c88fd.png)

All Files:
![image](https://cloud.githubusercontent.com/assets/4103847/10806420/851c0350-7dab-11e5-82b8-157fdf26d8b1.png)

**Comment by GraceAi** [comment]
Fixed. Please retest it after test site is updated.

**Comment by leeensminger** [comment]
Tested and confirmed OK
