### ISSUE TITLE
Delineation - Update Geometry - Updating shape of a new asset fails to save

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#73]
After creating a new asset, if the user updates the shape, the geometry update fails to save and an error is thrown.  This was confirmed in SHA dev environment.

To recreate:
1. Create a new delineation feature
2. Save the feature
3. Click Update Shape
4. Modify the shape
5. Click Save to save the update

The following error is thrown:
![image](https://cloud.githubusercontent.com/assets/4103847/10824954/1af0e034-7e39-11e5-905a-b0a65b1fd26b.png)

**Comment by GraceAi** [comment]
Fixed. Needs to update SP.

**Comment by leeensminger** [comment]
Tested and confirmed OK
