### ISSUE TITLE
Delineation - Project Name dropdown does not display values

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#76]
When you select Project Type = Delineation, the Projects dropdown menu is empty.  There should be at least 1 project, MD 24 Improvements.  This had been working in the previous production release, so it is likely a source data issue - but the data appears to be OK.

![image](https://cloud.githubusercontent.com/assets/4103847/12210327/1a175014-b627-11e5-8bc6-fd43bcdee693.png)

**Comment by johnshiu** [comment]
This should be resolved with the parent_project_id set to 0.
