### ISSUE TITLE
Selecting a feature in the feature manager returns IO Error

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#77]
When you select a feature in the feature manager, system returns an IO Error.  System continues to Autozoom and the feature is displayed normally.  This was not an issue in the previous production release.

![image](https://cloud.githubusercontent.com/assets/4103847/12210354/4b05cd04-b627-11e5-8d5d-cb4d3fee4099.png)

**Comment by johnshiu** [comment]
This is caused by the imported data having a null entry for SITE_CONSTRUCTION_ID for that asset. A blank entry is always created in that table when a new feature is created, so it couldn't find one when it hit the service.

I can fix this when the new data is loaded.
