### ISSUE TITLE
Delineation - Add New - Creating new feature results in ioError

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#8]
When creating a new Wetland or Stream feature, upon saving the feature attributes, the system fails during the create and displays an error message:

![image](https://cloud.githubusercontent.com/assets/4103847/10589353/dba383f4-7678-11e5-9b7e-99b9a2450b30.png)

To recreate:
1. Select a Study Area, Enable Editing, and click Add New
2. Select to Create New Features, click Next
3. Click Wetland or Stream feature type, click Next
4. Draw geometry, click Next
5. Populate required values, click Finish

**Comment by leeensminger** [comment]
The same issue results when attempting to create new assets from site selection features.  It seems likely to be the same fix for both areas, so leaving this as a comment for now.

**Comment by GraceAi** [comment]
Fixed. Please wait for retest.

**Comment by leeensminger** [comment]
Confirmed fixed
