### ISSUE TITLE
Update symbology/legend to differentiate assets, by field MITIGATION_ASSET

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#84]
Users would like to update map symbology, and the legend, to display each asset type differently, based on the common field MITIGATION_ASSET.

To exemplify, the symbology might be grouped like:

Mitigation Assets  _(where MITIGATION_ASSET = 1)_
     -Wetlands
     -Others
     -Streams

Non-Mitigation Assets _(where MITIGATION_ASSET = 2)_
     -Wetlands
     -Others
     -Streams

**Comment by johnshiu** [comment]
This is something that I would recommend we defer to a later date as I don't have access to the map server and it does not affect primary widget functionality. I can likely resume this item in mid-April.

**Comment by leeensminger** [comment]
Added to the enhancement list for development at that point.
