### ISSUE TITLE
Delineation - Delete Feature - Deleting Assets with dependencies triggers a popup error message

### ISSUE THREAD

**Issue by leeensminger** [leeensminger/OED_Wetlands#9]
Upon deleting assets with dependencies, the system correctly does not delete the asset.  The system displays a popup message, but it displays an IO error.

Please update the popup message to indicate to the user that "the feature cannot be deleted with an associated dependency."

![image](https://cloud.githubusercontent.com/assets/4103847/10603912/eed5f2ce-76ee-11e5-84ac-b8fce5a4d82e.png)

**Comment by GraceAi** [comment]
Fixed. Please wait for retest

**Comment by leeensminger** [comment]
Confirmed fixed
